# Generated by Django 5.2.9 on 2025-12-16 18:10

import django.db.models.deletion
import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_actor_id_alter_category_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteitem',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.favourite'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='image',
            field=models.ImageField(upload_to='movie_images', verbose_name=movie_app.models.Movie),
        ),
    ]
