# Generated by Django 5.2.9 on 2025-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_categorydetail_rename_category_categorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetail',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
