# Generated by Django 5.2.9 on 2025-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_categorydetail_description_categorylist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetail',
            name='category_name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='category_name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
