# Generated by Django 5.2.9 on 2025-12-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_remove_categorydetail_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='director_photo',
            new_name='actor_photo',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actor_movies', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='movie_app.movievideo'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_video', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_app.movievideo'),
        ),
    ]
